# Generated by Django 5.2.7 on 2025-11-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=50)),
                ('average', models.FloatField()),
                ('morality', models.FloatField()),
                ('performance', models.FloatField()),
            ],
        ),
    ]
