# Generated by Django 5.2.7 on 2025-11-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsModel',
            new_name='Students',
        ),
    ]
