# Generated by Django 5.2.7 on 2025-11-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_studentsmodel_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
