# Generated by Django 5.2.7 on 2025-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
