# Generated by Django 5.2.7 on 2025-11-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_students_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
