# Generated by Django 5.2.7 on 2025-11-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_students_full_name_alter_students_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='morality',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='performance',
            field=models.CharField(max_length=10),
        ),
    ]
