# Generated by Django 5.2.7 on 2025-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_students_morality_alter_students_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='class_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='morality',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='students',
            name='performance',
            field=models.CharField(max_length=15),
        ),
    ]
