# Generated by Django 5.2.7 on 2025-11-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_students_class_name_alter_students_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
