# Generated by Django 5.2.7 on 2025-11-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_students_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=225)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('birth_place', models.CharField(max_length=225)),
                ('nation', models.CharField(max_length=30)),
                ('recruitment_day', models.DateField()),
                ('job_title', models.CharField(max_length=225)),
                ('department', models.CharField(max_length=225)),
            ],
        ),
    ]
